### PR TITLE
Use sysstat instead of sysmetric.

### PR DESCRIPTION
**Pull request by clavoie-acquisio**

### CODE REVIEW

**Comment by AcquisioSysadmin** [comment]
Why the change sysmetric is the right one to use starting with 10g. sysstat is on it's long way out/

**Comment by clavoie-acquisio** [comment]
Dammit, sysstat is perfect for prometheus: it's counters that monotonically
increase from the start of the DB's process lifetime. It also has about 3x
more metrics than v$sysmetric

With v$sysmetrics the DB tries to be intelligent and recompute the interval
size everytime, which makes exporting to prometheus really painful --
dynamic intervals REALLY don't help. In particular, check the old
v$sysmetric query -- it converts the interval_size to a label -- the Oracle
docs I found let me think that there were two interval sizes: 15 seconds
and 60 seconds. So I make oracle_exporter export a single variable, with a
interval_size=15/60 label.

Except in reality, we have anything from 14 to 90 seconds interval.
V$sysmetric creates dozens of different timeseries (one per interval size)
and it makes it impossible to graph properly. As a bonus, sometimes if I'm
to believe prometheus, there's anywhere from 0 to 4 interval sizes at the
same time in v$sysmetric per query (and it changes over time), so I can't
just assume there's 2 intervals (a small and a big one).

Makes sense? Feels like an awkward explanation.

Christian

**Comment by AcquisioSysadmin** [comment]
It does make sense and we could swith it to sysstat since it still work in 11g and 12c.
My worries: 12c feature specific stats will not be implemented in v$sysstat.

If we are willing to take the risk, I will accept the merge.

What do you think?

**Comment by clavoie-acquisio** [comment]
It's a fairly big improvement over sysmetric, so please merge.

We should keep looking for a long-term solution, but I spent a few hours
looking at sysmetric timeseries on Friday, and found out that because of
the dynamic interval_size, it was mostly an exercise in frustration :(

On Mon, Jul 4, 2016 at 9:32 AM, Acquisio Sysadmin <notifications@github.com>
wrote:

> It does make sense and we could swith it to sysstat since it still work in
> 11g and 12c.
> My worries: 12c feature specific stats will not be implemented in
> v$sysstat.
>
> If we are willing to take the risk, I will accept the merge.
>
> What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acquisio/oracle_exporter/pull/2#issuecomment-230291576>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AStJnsaAEC9ABoE5UM5ZJ4s_MkYRluI6ks5qSQtpgaJpZM4JDcL6>
> .
>



-- 
Peace, Love and Unfinished Signatures,
Christian "Camembert" Lavoie

**Comment by clavoie-acquisio** [comment]
Danke.

On Mon, Jul 4, 2016 at 9:36 AM, Acquisio Sysadmin <notifications@github.com>
wrote:

> Merged #2 <https://github.com/Acquisio/oracle_exporter/pull/2>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acquisio/oracle_exporter/pull/2#event-712046705>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AStJnn1dxHIRJmMDBcJlORPzPAm34Y7Uks5qSQxlgaJpZM4JDcL6>
> .
>



-- 
Peace, Love and Unfinished Signatures,
Christian "Camembert" Lavoie

**Pull request merged**
